version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"

  # frontend:
  #   build: ./react-frontend
  #   command: ["npm", "start"]
  #   volumes:
  #     - ./react-frontend:/app/react-frontend
  #   ports:
  #     - "3000:3000"
